### ISSUE TITLE
Chatbot: Integrate Chatbot with Redis, Timeline: Zac' (30 min), Xiyao (Oct 6)

### ISSUE THREAD

**Issue by SabaO7** [SWRIL-AI-NLP-Translation/swril-chatbot#15]
Is redis the best way to go? 

the best way is to have redis (key:value) for caching and also storing for the short term and then have SQL as the backup.

**Comment by VionaWang** [comment]
Did some preliminary coding, will work for some testing to fix any issues and see if it works as intended

**Comment by VionaWang** [comment]
Done merging with Zac's code; will review with Zac to make sure it's aligned and may ask Kent to help with some testing

**Comment by VionaWang** [comment]
Working in progress on agent framework, estimated timeline will be Oct 6 as planned.

**Comment by VionaWang** [comment]
Finished integration on agent framework, will do some testing
